version: "3.8"
services:
  postgresql_data_container:
    image: 'postgres:15.2-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Intelligent-Forms
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgresql_data_container: